<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>2.0.0</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <RunAOTCompilation>True</RunAOTCompilation>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <RunAOTCompilation>True</RunAOTCompilation>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests\**" />
    <Content Remove="Tests\**" />
    <EmbeddedResource Remove="Tests\**" />
    <None Remove="Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.1" PrivateAssets="all" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.13.2" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.13.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.AspNetCore.Components.Web" />
    <Using Include="Microsoft.AspNetCore.Components.WebAssembly.Hosting" />
    <Using Include="Microsoft.FluentUI.AspNetCore.Components" />
    <Using Include="Microsoft.JSInterop" />
    <Using Include="Reci" />
    <Using Include="Reci.Core" />
    <Using Include="Reci.Data.Models" />
    <Using Include="Reci.Data.Repositories" />
    <Using Include="Reci.Data.Repositories.Interfaces" />
    <Using Include="Reci.Interfaces" />
    <Using Include="Reci.Services" />
    <Using Include="Reci.Services.Interfaces" />
    <Using Include="System.Collections.Concurrent" />
    <Using Include="System.IO.Compression" />
    <Using Include="System.Runtime.CompilerServices" />
    <Using Include="System.Text" />
    <Using Include="System.Text.Json" />
    <Using Include="System.Text.Json.Serialization" />
    <Using Include="System.Text.RegularExpressions" />
  </ItemGroup>
</Project>
