<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Resources\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.Playwright" Version="1.58.0" />
    <PackageReference Include="Microsoft.Playwright.Xunit.v3" Version="1.58.0" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Reci.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.Playwright" />
    <Using Include="Microsoft.Playwright.Xunit.v3" />
    <Using Include="System.Diagnostics" />
    <Using Include="System.Net" />
    <Using Include="System.Reflection" />
    <Using Include="System.Text.RegularExpressions" />
    <Using Include="Tests.Fixtures" />
    <Using Include="Tests.Utilities" />
    <Using Include="Xunit" />
    <Using Include="Reci.Core" />
    <Using Include="Reci.Data.Models" />
    <Using Include="Reci.Services" />
    <Using Include="Reci.Services.Interfaces" />
  </ItemGroup>

</Project>